name: WE
favicon: null
layout_spectrum: 0.9643846629187465
typography_spectrum: 0.14866176899522543
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.570869795512408
  lightness: 0.39941673330031335
  saturation: 0.6523301850538701
  rhythmicContrast: 0.1098929145373404
purpose: []
